import { useCallback, useEffect, useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { router, useLocalSearchParams } from 'expo-router'
import { getStudentId } from '@/lib/student'
import { supabase } from '@/lib/supabase'

type Exercise={id:string;titulo:string|null;enunciado:string;tipo:string;ordem:number}
type Alternative={id:string;exercicio_id:string;texto:string;ordem:number}

export default function ActivityDetailScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[exercises,setExercises]=useState<Exercise[]>([]);const[alts,setAlts]=useState<Record<string,Alternative[]>>({});const[answers,setAnswers]=useState<Record<string,{text:string;ids:string[]}>>({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{try{const studentId=await getStudentId();const{data:a,error:ae}=await supabase.from('atividades').select('id,titulo,descricao,status').eq('id',id).eq('aluno_id',studentId).single();if(ae)throw ae;setTitle(a.titulo);setDescription(a.descricao||'');const{data:e,error:ee}=await supabase.from('atividade_exercicios').select('id,titulo,enunciado,tipo,ordem').eq('atividade_id',id).order('ordem');if(ee)throw ee;setExercises(e??[]);const ids=(e??[]).map(x=>x.id);if(ids.length){const{data:v,error:ve}=await supabase.from('exercicio_alternativas').select('id,exercicio_id,texto,ordem').in('exercicio_id',ids).order('ordem');if(ve)throw ve;const grouped:Record<string,Alternative[]>={};for(const x of v??[])(grouped[x.exercicio_id]??=[]).push(x);setAlts(grouped)}}catch(e){Alert.alert('Atividade',e instanceof Error?e.message:'Não foi possível carregar a atividade.');router.back()}finally{setLoading(false)}},[id])
 useEffect(()=>{void load()},[load])
 function toggle(exerciseId:string,alternativeId:string,single:boolean){setAnswers(p=>{const c=p[exerciseId]??{text:'',ids:[]};const ids=single?(c.ids.includes(alternativeId)?[]:[alternativeId]):(c.ids.includes(alternativeId)?c.ids.filter(x=>x!==alternativeId):[...c.ids,alternativeId]);return{...p,[exerciseId]:{...c,ids}}})}
 async function submit(){if(!id)return;setSaving(true);try{const studentId=await getStudentId();const{data:current,error:ce}=await supabase.from('respostas_aluno').select('id').eq('atividade_id',id).eq('aluno_id',studentId);if(ce)throw ce;const oldIds=(current??[]).map(x=>x.id);if(oldIds.length){const{error}=await supabase.from('respostas_aluno').delete().in('id',oldIds);if(error)throw error}const rows=exercises.map(e=>{const a=answers[e.id]??{text:'',ids:[]};const objective=['multipla_escolha','multipla_resposta','verdadeiro_falso'].includes(e.tipo);return{atividade_id:id,exercicio_id:e.id,aluno_id:studentId,resposta_texto:objective?(a.ids.length>1?JSON.stringify(a.ids):null):(a.text.trim()||null),alternativa_id:objective&&(e.tipo==='multipla_escolha'||e.tipo==='verdadeiro_falso')?(a.ids[0]||null):null,pontuacao:null,feedback:null,corrigida:false}});if(rows.length){const{error}=await supabase.from('respostas_aluno').insert(rows);if(error)throw error}const{data:updated,error:ue}=await supabase.from('atividades').update({status:'respondida',updated_at:new Date().toISOString()}).eq('id',id).eq('aluno_id',studentId).select('id,status').maybeSingle();if(ue)throw ue;if(!updated||updated.status!=='respondida')throw new Error('Não foi possível confirmar o envio da atividade.');Alert.alert('Atividade','Atividade enviada com sucesso.');router.back()}catch(e){Alert.alert('Atividade',e instanceof Error?e.message:'Não foi possível enviar a atividade.')}finally{setSaving(false)}}
 if(loading)return<View style={styles.loading}><ActivityIndicator size="large"/></View>
 return<ScrollView style={styles.container} contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Voltar</Text></Pressable><Text style={styles.title}>{title}</Text>{description?<Text style={styles.description}>{description}</Text>:null}{exercises.map((e,i)=>{const options=alts[e.id]??[];const single=e.tipo==='multipla_escolha'||e.tipo==='verdadeiro_falso';return<View key={e.id} style={styles.exercise}><Text style={styles.number}>QUESTÃO {i+1}</Text>{e.titulo?<Text style={styles.exerciseTitle}>{e.titulo}</Text>:null}<Text style={styles.question}>{e.enunciado}</Text>{options.map(o=>{const selected=answers[e.id]?.ids.includes(o.id);return<Pressable key={o.id} style={[styles.option,selected&&styles.selected]} onPress={()=>toggle(e.id,o.id,single)}><Text style={styles.optionText}>{o.texto}</Text></Pressable>})}{!options.length?<TextInput style={styles.input} multiline placeholder="Digite sua resposta..." value={answers[e.id]?.text??''} onChangeText={text=>setAnswers(p=>({...p,[e.id]:{text,ids:p[e.id]?.ids??[]}}))}/>:null}</View>})}<Pressable style={styles.submit} disabled={saving} onPress={()=>void submit()}><Text style={styles.submitText}>{saving?'Enviando...':'Enviar atividade'}</Text></Pressable></ScrollView>
}
const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#f6f7fb'},container:{flex:1,backgroundColor:'#f6f7fb'},content:{padding:24,paddingTop:52,paddingBottom:50},back:{color:'#2563eb',fontWeight:'700',marginBottom:18},title:{fontSize:28,fontWeight:'800',color:'#111827'},description:{marginTop:8,color:'#667085',lineHeight:21,marginBottom:20},exercise:{backgroundColor:'#fff',borderRadius:18,padding:18,marginBottom:12},number:{fontSize:11,fontWeight:'800',color:'#667085',letterSpacing:1},exerciseTitle:{fontSize:16,fontWeight:'800',color:'#111827',marginTop:8},question:{fontSize:17,fontWeight:'700',color:'#111827',lineHeight:23,marginTop:8,marginBottom:14},option:{borderWidth:1,borderColor:'#d9dde5',borderRadius:12,padding:14,marginTop:8},selected:{borderColor:'#111827',backgroundColor:'#f2f4f7'},optionText:{color:'#344054',lineHeight:20},input:{minHeight:110,borderWidth:1,borderColor:'#d9dde5',borderRadius:12,padding:14,textAlignVertical:'top'},submit:{height:52,borderRadius:14,backgroundColor:'#111827',alignItems:'center',justifyContent:'center',marginTop:8},submitText:{color:'#fff',fontWeight:'800'}})
